### ISSUE TITLE
Bouncer links not activating the Chrome extension when group is Public

### ISSUE THREAD

**Issue by klemay** [hypothesis/bouncer#323]
## Summary

If you follow a bouncer link in a browser where the Chrome extension is installed, the extension doesn't activate once the link resolves. 

## Steps to reproduce

1. Get a Bouncer link for the Public channel for a PDF or web page. Three that we've tested with are:
- <https://hyp.is/go?url=https%3A%2F%2Fcontent.govdelivery.com%2Fattachments%2FMIEOG%2F2020%2F04%2F02%2Ffile_attachments%2F1417518%2FEO%25202020-35.pdf&group=__world__>
- <https://hyp.is/go?url=https%3A%2F%2Fd242fdlp0qlcia.cloudfront.net%2Fuploads%2F2019%2F02%2F08123342%2FHypothesis-VPAT-2019.02.04.pdf&group=__world__>
- https://en.wikipedia.org/wiki/Buridan%27s_bridge

2. In a browser where the Chrome extension is installed, follow that link

## Expected behavior
The Chrome extension activates and the sidebar opens

## Actual behavior
The extension is not activated. You have to manually turn it on:

<img width="1552" alt="Screen Shot 2020-04-02 at 5 12 05 PM" src="https://user-images.githubusercontent.com/12087705/78300221-22f52980-7505-11ea-81a5-8a424a61f565.png">

## Notes

Strangely, we don't see this problem with private groups. You can [join this private group](https://hypothes.is/groups/Bd1pN47n/abc-internal-testing) and it'll work properly. See:
- https://hyp.is/go?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FBuridan%2527s_bridge&group=Bd1pN47n
- https://hyp.is/go?url=https%3A%2F%2Fcontent.govdelivery.com%2Fattachments%2FMIEOG%2F2020%2F04%2F02%2Ffile_attachments%2F1417518%2FEO%25202020-35.pdf&group=Bd1pN47n
- https://hyp.is/go?url=https%3A%2F%2Fd242fdlp0qlcia.cloudfront.net%2Fuploads%2F2019%2F02%2F08123342%2FHypothesis-VPAT-2019.02.04.pdf&group=Bd1pN47n

It's also working properly for publisher groups. See:
https://hyp.is/go?url=https%3A%2F%2Fmodernismmodernity.org%2Fforums%2Fposts%2Fresponses-responses-special-issue-weak-theory&group=q9iV3JLd

...so this appears to be isolated to the Public channel.

**Comment by robertknight** [comment]
This has been broken forever. The Public group has an ID of `__world__` and it looks like the extension's URL fragment matching doesn't allow for underscores in the group ID: https://github.com/hypothesis/browser-extension/blob/b1232162db9794296632c564aec7229a952c6679/src/background/direct-link-query.js#L41

**Comment by robertknight** [comment]
@klemay - Aside from the issue in the browser extension I noticed that the links in the original issue description got corrupted when GitHub turned the URLs into links, as the trailing underscores got removed. In markdown you can avoid this by surrounding the link with `<` and `>`.
