### ISSUE TITLE
Add docdrop.org/* to url patterns to not proxy.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/bouncer#389]
We shouldn't proxy docdrop pages, since the client is already embedded there.  The recent change to not proxy the youtube domain has exacerbated the issue.  

https://twitter.com/ChrisAndrewsEdu/status/1354156722349342722

**Comment by robertknight** [comment]
@dwhly - Can you confirm exactly which URL patterns should be used here? I have added the whole of `docdrop.org` at https://github.com/hypothesis/bouncer/pull/390 but if it needs to be more narrowly scoped, let me know.
