### ISSUE TITLE
Support group: as a parameter 

### ISSUE THREAD

**Issue by dwhly** [hypothesis/bouncer#51]
In https://github.com/hypothesis/bouncer/pull/48 @robertknight says:

> group:{pubid} - No, not yet. I do understand that this would be very useful. It does surface some issues that we'll need to address or have a reasonable idea of what we might do later, such as how to handle the case where the current user is not a member of the group and will we ever support multiple groups. Could you file an issue?

Questions:

**What if the current user is not a member of the group** 

If they follow a hyp.is link that specifies a group they're not a member of, they should be taken to the indicated page, but the target group annotations obviously cannot and presumably should not be shown to them.  For now, I don't think they should auto-join the group, though I can imagine that groups which are more open might be able to be configured to allow auto-joining.

In the event that they're not a member, perhaps a card or alert is shown that says "you don't have permission to view annotations in group XXX".

**Will we ever support multiple groups (being specified as params)**

Possibly-- though I imagine the overwhelming use case here is a single group.  For sure multiple groups is not a first requirement.  Do we need to determine now?

**Comment by chdorner** [comment]
This is a feature that needs to be implemented in the client. bouncer just forwards whatever the query is and the client then interprets it.

**Comment by dwhly** [comment]
Closing in favor of: https://github.com/hypothesis/client/issues/488
