### ISSUE TITLE
Check chrome.runtime.lastError

### ISSUE THREAD

**Issue by seanh** [hypothesis/bouncer#9]
Rob: Looking at the JS code, I do see an issue that we're not checking `chrome.runtime.lastError` in the sendMessage callback

**Comment by seanh** [comment]
@robertknight What would we do with `lastError` here? I can't imagine what errors we might get here, but I guess we should just redirect to via instead of the Chrome extension, if `lastError` is defined?

**Comment by robertknight** [comment]
@seanh I'd suggest logging the error with `console.error()` and then redirecting the user through Via.
